CREATE DATABASE its_31_08_mtm_recap;
USE its_31_08_mtm_recap;

CREATE TABLE Cliente(
	clienteID INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(250) NOT NULL,
    cognome VARCHAR(250) NOT NULL,
    indirizzo VARCHAR(500) NOT NULL,
    cod_fis CHAR(16) NOT NULL UNIQUE
);

CREATE TABLE Conto(
	contoID INTEGER PRIMARY KEY AUTO_INCREMENT,
    iban VARCHAR(250) NOT NULL UNIQUE,
    saldo DECIMAL(5, 2) DEFAULT 0
);

CREATE TABLE Cliente_Conto(
	clienteRIF INTEGER NOT NULL,
    contoRIF INTEGER NOT NULL,
    FOREIGN KEY (clienteRIF) REFERENCES Cliente(clienteID) ON DELETE CASCADE,
    FOREIGN KEY (contoRIF) REFERENCES Conto(contoID) ON DELETE CASCADE,
    PRIMARY KEY (clienteRIF, contoRIF)
);

CREATE TABLE Carta(
	cartaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    numero INTEGER(16) NOT NULL UNIQUE,
    scadenza DATE, -- CHECK (scadenza > SELECT CURRENT_TIMESTAMP),
    clienteRIF INTEGER NOT NULL,
    contoRIF INTEGER NOT NULL,
    FOREIGN KEY (clienteRIF) REFERENCES Cliente(clienteID) ON DELETE CASCADE,
    FOREIGN KEY (contoRIF) REFERENCES Conto(contoID) ON DELETE CASCADE
);

